""" フォント設定
if has('win32') || has('win64')
    set guifont=MyricaM_M:h16:cSHIFTJIS:qDRAFT,Ricty_Diminished_Discord:h16:cSHIFTJIS:qDRAFT,ＭＳ_ゴシック:h12:cSHIFTJIS:qDRAFT
else
    set guifont=MyricaM M\ 13,Ricty_Diminished_Discord\ 13
endif

