""" フォント設定
if has('win32') || has('win64')
    set guifont=MyricaM_M:h16:cSHIFTJIS:qDRAFT,Ricty_Diminished_Discord:h16:cSHIFTJIS:qDRAFT,ＭＳ_ゴシック:h12:cSHIFTJIS:qDRAFT
else
    set guifont=MyricaM M\ 13,Ricty_Diminished_Discord\ 13
endif

nnoremap <C-ScrollWheelUp> :call AddGuifontSize(1)<Enter>
nnoremap <C-ScrollWheelDown> :call AddGuifontSize(-1)<Enter>

function! SetGuiFont(new_guifont)
  let &guifont = a:new_guifont
endfunction

""" {{{ for windows position save
""" from [vim-jp » Hack #120: gVim でウィンドウの位置とサイズを記憶する](http://vim-jp.org/vim-users-jp/2010/01/28/Hack-120.html)
let g:save_window_file = expand(g:myvimfiles . '/winpos')
augroup SaveWindow
  autocmd!
  autocmd VimLeavePre * call s:save_window()
  function! s:save_window()
    let options = [
      \ 'set columns=' . &columns,
      \ 'set lines=' . &lines,
      \ 'winpos ' . getwinposx() . ' ' . getwinposy(),
      \ ]
    call writefile(options, g:save_window_file)
  endfunction
augroup END

if filereadable(g:save_window_file)
  execute 'source' g:save_window_file
endif
""" }}} for windows position save

