  postgres:
    image: postgres:14.5
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 0.0.0.0:5432:5432

